import {
  HostPrivilegeRequest,
  VoiceProfile,
  GameRunSummary,
  GameTemplate,
  AdminStats,
} from '../types/admin';

// ─── Admin Dashboard Stats ───
export const mockAdminStats: AdminStats = {
  totalGamesThisMonth: 12,
  activeGamesNow: 1,
  totalPlayers: 187,
  pendingHostRequests: 3,
  pendingVoiceApprovals: 1,
  rewardsFulfilled: 28,
};

// ─── Host Privilege Requests ───
export const mockHostRequests: HostPrivilegeRequest[] = [
  {
    id: 'hr-1',
    requesterName: 'Priya Sharma',
    requesterEmail: 'priya.sharma@cgi.com',
    requestedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    reason: 'I want to run weekly bingo for the Montréal delivery team (25 people).',
    status: 'Pending',
  },
  {
    id: 'hr-2',
    requesterName: 'James O\'Brien',
    requesterEmail: 'james.obrien@cgi.com',
    requestedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    reason: 'Planning a quarterly team building event with bingo for ~50 people.',
    status: 'Pending',
  },
  {
    id: 'hr-3',
    requesterName: 'Maria Gonzalez',
    requesterEmail: 'maria.gonzalez@cgi.com',
    requestedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    reason: 'Running a fun Friday activity for our project team.',
    status: 'Pending',
  },
  {
    id: 'hr-4',
    requesterName: 'Kevin Zhang',
    requesterEmail: 'kevin.zhang@cgi.com',
    requestedAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    reason: 'Team engagement activity for Toronto office.',
    status: 'Approved',
    reviewedAt: new Date(Date.now() - 12 * 86400000).toISOString(),
    reviewedBy: 'Admin Team',
  },
  {
    id: 'hr-5',
    requesterName: 'Sophie Martin',
    requesterEmail: 'sophie.martin@cgi.com',
    requestedAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    reason: 'Wanted to test the platform.',
    status: 'Rejected',
    reviewedAt: new Date(Date.now() - 18 * 86400000).toISOString(),
    reviewedBy: 'Admin Team',
  },
];

// ─── Voice Profiles ───
export const mockVoiceProfiles: VoiceProfile[] = [
  {
    id: 'vp-1',
    employeeName: 'David Thompson',
    employeeEmail: 'david.thompson@cgi.com',
    status: 'Active',
    consentRecordedAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    approvedBy: 'Admin Team',
    approvedAt: new Date(Date.now() - 28 * 86400000).toISOString(),
    lastUsedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    usageCount: 8,
  },
  {
    id: 'vp-2',
    employeeName: 'Emily Wilson',
    employeeEmail: 'emily.wilson@cgi.com',
    status: 'Active',
    consentRecordedAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    approvedBy: 'Admin Team',
    approvedAt: new Date(Date.now() - 18 * 86400000).toISOString(),
    lastUsedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    usageCount: 3,
  },
  {
    id: 'vp-3',
    employeeName: 'Nathan Roy',
    employeeEmail: 'nathan.roy@cgi.com',
    status: 'Pending Consent',
    usageCount: 0,
  },
  {
    id: 'vp-4',
    employeeName: 'Lisa Park',
    employeeEmail: 'lisa.park@cgi.com',
    status: 'Revoked',
    consentRecordedAt: new Date(Date.now() - 60 * 86400000).toISOString(),
    approvedBy: 'Admin Team',
    approvedAt: new Date(Date.now() - 58 * 86400000).toISOString(),
    usageCount: 12,
  },
];

// ─── Game Runs (Admin view) ───
export const mockGameRuns: GameRunSummary[] = [
  {
    id: 'gr-1',
    templateName: 'Friday Fun Bingo',
    hostName: 'Kevin Zhang',
    scheduledAt: new Date(Date.now() + 2 * 86400000).toISOString(),
    status: 'Scheduled',
    playerCount: 0,
    winnersCount: 0,
  },
  {
    id: 'gr-2',
    templateName: 'Friday Fun Bingo',
    hostName: 'Kevin Zhang',
    scheduledAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    status: 'Complete',
    playerCount: 32,
    winnersCount: 3,
  },
  {
    id: 'gr-3',
    templateName: 'Monthly All-Hands Bingo',
    hostName: 'Admin Team',
    scheduledAt: new Date().toISOString(),
    status: 'Live',
    playerCount: 48,
    winnersCount: 1,
  },
  {
    id: 'gr-4',
    templateName: 'Sprint Retro Bingo',
    hostName: 'Maria Gonzalez',
    scheduledAt: new Date(Date.now() - 12 * 86400000).toISOString(),
    status: 'Complete',
    playerCount: 18,
    winnersCount: 3,
  },
  {
    id: 'gr-5',
    templateName: 'Quarterly Team Building',
    hostName: 'James O\'Brien',
    scheduledAt: new Date(Date.now() - 25 * 86400000).toISOString(),
    status: 'Cancelled',
    playerCount: 4,
    winnersCount: 0,
  },
  {
    id: 'gr-6',
    templateName: 'Friday Fun Bingo',
    hostName: 'Kevin Zhang',
    scheduledAt: new Date(Date.now() + 9 * 86400000).toISOString(),
    status: 'Content Generating',
    playerCount: 0,
    winnersCount: 0,
  },
];

// ─── Game Templates ───
export const mockGameTemplates: GameTemplate[] = [
  {
    id: 'tmpl-1',
    name: 'Friday Fun Bingo',
    hostName: 'Admin Team',
    recurrence: 'Weekly',
    dayOfWeek: 'Friday',
    time: '3:00 PM',
    timezone: 'America/Toronto',
    audienceSize: 35,
    contentMode: 'AI Generated',
    voiceMode: 'Auto Select',
    minPlayers: 6,
    prizeEnabled: true,
    prizeValue: '$25 Gift Card',
    nextRunAt: new Date(Date.now() + 2 * 86400000).toISOString(),
    totalRuns: 8,
    isActive: true,
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
  },
  {
    id: 'tmpl-2',
    name: 'Monthly All-Hands Bingo',
    hostName: 'Admin Team',
    recurrence: 'Monthly',
    dayOfWeek: 'Last Thursday',
    time: '2:00 PM',
    timezone: 'America/Toronto',
    audienceSize: 75,
    contentMode: 'AI Generated',
    voiceMode: 'Default Neural',
    minPlayers: 10,
    prizeEnabled: true,
    prizeValue: '$50 Gift Card',
    nextRunAt: new Date(Date.now() + 10 * 86400000).toISOString(),
    totalRuns: 3,
    isActive: true,
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
  },
  {
    id: 'tmpl-3',
    name: 'Sprint Retro Bingo',
    hostName: 'Admin Team',
    recurrence: 'Bi-Weekly',
    dayOfWeek: 'Wednesday',
    time: '4:30 PM',
    timezone: 'America/Toronto',
    audienceSize: 20,
    contentMode: 'Manual',
    voiceMode: 'Employee Voice',
    minPlayers: 5,
    prizeEnabled: false,
    totalRuns: 12,
    isActive: false,
    createdAt: new Date(Date.now() - 180 * 86400000).toISOString(),
  },
];

// ─── AI Content Review Mock Data ───
export const mockWordSet = {
  id: 'ws-1',
  gameRunId: 'gr-1',
  templateName: 'Friday Fun Bingo',
  generatedAt: new Date(Date.now() - 3600000).toISOString(),
  prompt: 'Generate 30 fun corporate buzzwords and office culture phrases that employees will recognize.',
  status: 'Pending Review' as const,
  words: [
    { id: 'wd-1', word: 'Synergy', approved: true, flagged: false },
    { id: 'wd-2', word: 'Circle Back', approved: true, flagged: false },
    { id: 'wd-3', word: 'Deep Dive', approved: true, flagged: false },
    { id: 'wd-4', word: 'Touch Base', approved: true, flagged: false },
    { id: 'wd-5', word: 'Action Item', approved: true, flagged: false },
    { id: 'wd-6', word: 'Bandwidth', approved: true, flagged: false },
    { id: 'wd-7', word: 'Pivot', approved: true, flagged: false },
    { id: 'wd-8', word: 'Ideate', approved: true, flagged: false },
    { id: 'wd-9', word: 'Leverage', approved: true, flagged: false },
    { id: 'wd-10', word: 'Hard Stop', approved: true, flagged: false },
    { id: 'wd-11', word: 'Buy-in', approved: true, flagged: false },
    { id: 'wd-12', word: 'Deliverable', approved: true, flagged: false },
    { id: 'wd-13', word: 'Ecosystem', approved: true, flagged: false },
    { id: 'wd-14', word: 'Scalable', approved: true, flagged: false },
    { id: 'wd-15', word: 'Pain Point', approved: true, flagged: false },
    { id: 'wd-16', word: 'Moving Forward', approved: true, flagged: false },
    { id: 'wd-17', word: 'On My Radar', approved: true, flagged: false },
    { id: 'wd-18', word: 'Low-Hanging Fruit', approved: true, flagged: false },
    { id: 'wd-19', word: 'Value Add', approved: true, flagged: false },
    { id: 'wd-20', word: 'Ping Me', approved: true, flagged: false },
    { id: 'wd-21', word: 'Reach Out', approved: true, flagged: false },
    { id: 'wd-22', word: 'Take Offline', approved: true, flagged: false },
    { id: 'wd-23', word: 'Game Changer', approved: true, flagged: false },
    { id: 'wd-24', word: 'Drill Down', approved: true, flagged: false },
    { id: 'wd-25', word: 'Boil The Ocean', approved: true, flagged: true },
  ],
};
